name: Simple CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Run Test
        run: echo "Code checked successfully"
        
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 82.112.238.89
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "/home/deploy/file"
          script_components: 1
